# Generated by Django 6.0.3 on 2026-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedorganization',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='managedorganization',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managedplan',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='managedplan',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managedsubscription',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='managedsubscription',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
