# Generated by Django 6.0.3 on 2026-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_center', '0002_managedorganization_last_sync_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySyncKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=120, unique=True)),
                ('algorithm', models.CharField(choices=[('ed25519', 'Ed25519')], default='ed25519', max_length=20)),
                ('private_key_pem', models.TextField()),
                ('public_key_pem', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
